# Site settings
title: Himanshu’s Blog
header-img: img/home-bg.jpg
email: himanshudedge@gmail.com
description: ““
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  himanshudedge
facebook_username:  himanshu.dedge

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
pagination: true
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
